#Consider the below code to answer further questions:
#import numpy as np
#list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
#array_list = np.array(object = list_)
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
#to print the data types of both the variables.

#ANS:-

In [1]:
import numpy as np

In [2]:
list_=['1','2','3','4','5']

In [3]:
array_list=np.array(list_)

# There is difernce between the data types of both list and array_list

In [8]:
print(f"the data type of list is {type(list_)}")
print()
print(f"the data type of array_list is {array_list.dtype}")

the data type of list is <class 'list'>

the data type of array_list is <U1


In [9]:
for i in list_ :
  print(type(i))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

#ANS:-

In [10]:
l1=[]
for i in list_:
  print(type(i))
  l1.append(type(i))

print()
print(l1)


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

[<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]


In [11]:
print(f"my array_list is {array_list}")

my array_list is ['1' '2' '3' '4' '5']


In [16]:
l3=[]
for i in array_list:
  print(type(i))
  l3.append(type(i))

x=np.array(l3)
print()

print()
print(f"the array of types of data inside array_list is {x}")

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


the array of types of data inside array_list is [<class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.str_'>
 <class 'numpy.str_'> <class 'numpy.str_'>]
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


the array of types of data inside array_list is [<class 'numpy.str_'> <class 'numpy.str_'> <class 'numpy.str_'>
 <class 'numpy.str_'> <class 'numpy.str_'>]


# Q3. Considering the following changes in the variable, array_list:
#array_list = np.array(object = list_, dtype = int)
#Will there be any difference in the data type of the elements present in both the variables, list_ and
#arra_list? If so then print the data types of each and every element present in  both the variables, list_
#and arra_list.

# ANS:-

In [23]:
array_list=np.array(list_,dtype=int)

In [18]:
print(f"now my array has become this {array_list}")

now my array has become this [1 2 3 4 5]


In [19]:
print(f"But my list_ is still the same like before {list_}")

But my list_ is still the same like before ['1', '2', '3', '4', '5']


let's check type of data inside the list_ and array_list

In [20]:
store_data_type_of_list=[]
for i in list_:
  print(type(i))
  store_data_type_of_list.append(type(i))

print()
print()
print(f"the type of data inside list_ is given by this list {store_data_type_of_list}")

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


the type of data inside list_ is given by this list [<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]


In [24]:
store_data_type_of_array_list=[]
for i in array_list:
  print(type(i))
  store_data_type_of_array_list.append(type(i))

print()
print()
print(f"the type of data inside store_data_type_of_arraylist is given by this array {np.array(store_data_type_of_array_list)}")

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


the type of data inside store_data_type_of_arraylist is given by this array [<class 'numpy.int64'> <class 'numpy.int64'> <class 'numpy.int64'>
 <class 'numpy.int64'> <class 'numpy.int64'>]


#Consider the below code to answer further questions:
#import numpy as np
#num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
#num_array = np.array(object = num_list)
#Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape
#(ii) size

# ANS:-

In [25]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

In [26]:
num_array = np.array(object = num_list)

In [28]:
print(f"The shape of num_array is {num_array.shape}")

The shape of num_array is (2, 3)


In [29]:
print(f"The size of num_array is {num_array.size}")

The size of num_array is 6


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
#creation function.
#[Hint: The size of the array will be 9 and the shape will be (3,3).]

# ANS:-

In [30]:
import numpy as np


zero_matrix = np.zeros((3, 3))

print(f"3x3 Matrix of Zeros:{zero_matrix}")


3x3 Matrix of Zeros:[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [31]:
identity_matrix = np.identity(5)

print(f"5x5 Identity Matrix:{identity_matrix}")

5x5 Identity Matrix:[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
